# Generated by Django 4.0.5 on 2022-06-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
