# Generated by Django 4.0.5 on 2022-06-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('instagram', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/about_us')),
            ],
            options={
                'verbose_name_plural': 'aboutus',
            },
        ),
    ]
