# Generated by Django 4.0.6 on 2022-07-26 16:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 16, 26, 30, 996483, tzinfo=utc)),
        ),
    ]
