# Generated by Django 4.0.5 on 2022-06-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_teammember_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='username',
            new_name='user',
        ),
    ]
