# Generated by Django 4.0.5 on 2022-07-04 16:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_teammember_github_teammember_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 7, 4, 16, 16, 41, 358514, tzinfo=utc))),
            ],
        ),
    ]
