# Generated by Django 4.0.5 on 2022-07-09 14:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 9, 14, 52, 11, 901416, tzinfo=utc)),
        ),
    ]
